ansible_host: 192.168.219.4
ansible_user: root
ansible_password: odroid
desired_ip: 192.168.219.4
gateway_ip: 192.168.219.1

iptables_use_nfs: true

is_k8s_master: true
k8s_node_labels:
  - "homelab.bhyoo.com/zfs-node=true"
  - "homelab.bhyoo.com/zfs-pool-slow-hot-storage=true"


wireguard_ip: "10.222.0.2"


allow_ssh_root_login: true
