ansible_host: 192.168.219.5
ansible_user: bhyoo
desired_ip: 192.168.219.5
gateway_ip: 192.168.219.1

# k8s
is_k8s_master: true
k8s_node_labels:
  - "homelab.bhyoo.com/vpn-gateway=true"

# iptables-firewall
is_wireguard_gateway: true
iptables_use_ftp: true

# wireguard_mesh
wireguard_ip: "10.222.0.3"
